config/routes.rb
Rails.application.routes.draw do

  resources :department_entry_memberships
  resources :department_entries do
    collection do
      post :fetch_users
    end
  end

  resources :favourites

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings
  get 'pending_approval' => 'pages#pending_approval', as: :pending_approval
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'newsfeed' => 'pages#newsfeed', as: :newsfeed
  get 'summary' => 'pages#summary', as: :summary
  get 'load_pictures' => 'pages#load_pictures', as: :picture
  get 'search' => 'pages#search', as: :search
  get 'price' => 'pages#price', as: :price
  get 'contact_us' => 'pages#contact_us', as: :contact_us
  post 'email_us' => 'pages#email_us', as: :email_us

  resources :subscriptions

  resources :tag_entries

  resources :opinions

  resources :beta_sign_ups, only: [:index, :create] do
    member do
      get :approve
      get :deny
      get :register
    end
  end

  resources :comments do
    collection do
      get :filter_sort
    end
  end

  resources :pictures
  resources :posts do
    member do
      post :judge
    end
  end

  resources :project_memberships do
    member do
      get :toggle
    end
  end

  resources :projects do
    collection do
      post :join_by_code
    end
    member do
      post :show
      get :management
      get :generate_code
    end
  end

  resources :organizations do
    member do
      get :toggle
      get :manage_users
      post :manage_users
      post :update_departments
    end
  end

  resources :user_sessions

  resources :users do
    member do
      get :my_organization
    end

    collection do
      get :autocomplete_user_email
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :username
  belongs_to :organization
  has_many :posts
  has_many :tags, through: :posts

  has_many :project_memberships, dependent: :destroy
  has_many :users, through: :project_memberships
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :generate_code, :management, :search]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if params[:query]
      raise
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def management
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.access_code = ('a'..'z').to_a.shuffle[0,32].join

    respond_to do |format|
      if @project.save
        ProjectMembership.create(user_id: current_user.id, project_id: @project.id, admin: true)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_code
    @project.access_code = ('a'..'z').to_a.shuffle[0,32].join
    @project.save
    redirect_to @project, notice: 'New access code generated.'
  end

  def join_by_code
    target_organization = Project.where(name: params[:name]).first

    if target_organization.nil?
      redirect_to :back, notice: 'Project does not exist.' and return
    end

    if target_organization.access_code != params[:access_code]
      redirect_to :back, notice: 'Wrong access code.' and return
    end

    ProjectMembership.create(organization_id: target_organization.id, user_id: params[:user_id], admin: false)
    redirect_to target_organization, notice: 'Successfully joined organization.'
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      @organization = @project.organization
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :access_code, :threshold, :organization_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def count_opinion(opinionable)
    opinionable.opinions.like.count - opinionable.opinions.dislike.count
  end
end

app/views/projects/_card.html.haml
.project-card
  %h4
    = project.name
  - if can? :manage, project.organization || project.users.include?(current_user)
    = link_to project do
      View Project
  - else
    %p
      No Access
    = form_tag join_by_code_projects_path, class: "form-inline" do
      = hidden_field_tag :user_id, current_user.id
      = hidden_field_tag :project_id, project.id
      .form-group
        = text_field_tag :access_code, nil, class: "form-control", placeholder: "Enter access code ..."
      = submit_tag "Join", class: "btn btn-sm btn-success"

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :organization_id, value: params[:organization_id]
  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :threshold
    = f.number_field :threshold, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Access code
    %th Threshold
    %th Organization
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.access_code
      %td= project.threshold
      %td= project.organization_id
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/management.html.haml
%h2
  = @project.name
  - if can? :update, @project
    = link_to edit_organization_path(@project) do
      .fa.fa-edit

- if can? :manage, @project
  %h5
    %b Access code:
    = @project.access_code
%p
  %b Threshold:
  = @project.threshold

%hr

app/views/projects/new.html.haml
%h1 New project

= render 'form'

app/views/projects/show.html.haml
= render 'layouts/discussion'