config/routes.rb
Rails.application.routes.draw do

  resources :department_entry_memberships
  resources :department_entries do
    collection do
      post :fetch_users
    end
  end

  resources :favourites

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings
  get 'pending_approval' => 'pages#pending_approval', as: :pending_approval
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'newsfeed' => 'pages#newsfeed', as: :newsfeed
  get 'summary' => 'pages#summary', as: :summary
  get 'load_pictures' => 'pages#load_pictures', as: :picture
  get 'search' => 'pages#search', as: :search
  get 'price' => 'pages#price', as: :price
  get 'contact_us' => 'pages#contact_us', as: :contact_us
  post 'email_us' => 'pages#email_us', as: :email_us

  resources :subscriptions

  resources :tag_entries

  resources :opinions

  resources :beta_sign_ups, only: [:index, :create] do
    member do
      get :approve
      get :deny
      get :register
    end
  end

  resources :comments do
    collection do
      get :filter_sort
    end
  end

  resources :pictures
  resources :posts do
    member do
      post :judge
    end
  end

  resources :project_memberships do
    member do
      get :toggle
    end
  end

  resources :projects do
    collection do
      post :join_by_code
    end
    member do
      post :show
      get :management
      get :generate_code
    end
  end

  resources :organizations do
    member do
      get :toggle
      get :manage_users
      post :manage_users
      post :update_departments
    end
  end

  resources :user_sessions

  resources :users do
    member do
      get :my_organization
    end

    collection do
      get :autocomplete_user_email
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :organization

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to :root, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to :back}
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email, :note, :active)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.haml
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      %ul
        - @subscription.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :note
    = f.text_area :note
  .actions
    = f.submit 'Save'

app/views/subscriptions/edit.html.haml
%h1 Editing subscription

= render 'form'

= link_to 'Show', @subscription
\|
= link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.haml
.container{style: 'margin-top: 90px'}
  %h1 Listing subscriptions

  %table.table.table-bordered
    %tr
      %th Email
      %th Note
      %th
      %th
      %th

    - @subscriptions.each do |subscription|
      %tr
        %td= subscription.email
        %td= subscription.note
        %td= link_to 'Show', subscription
        %td= link_to 'Edit', edit_subscription_path(subscription)
        %td= link_to 'Destroy', subscription, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/subscriptions/new.html.haml
%h1 New subscription

= render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @subscription.email
%p
  %b Note:
  = @subscription.note

= link_to 'Edit', edit_subscription_path(@subscription)
\|
= link_to 'Back', subscriptions_path