config/routes.rb
Rails.application.routes.draw do

  resources :department_entry_memberships
  resources :department_entries do
    collection do
      post :fetch_users
    end
  end

  resources :favourites

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings
  get 'pending_approval' => 'pages#pending_approval', as: :pending_approval
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'newsfeed' => 'pages#newsfeed', as: :newsfeed
  get 'summary' => 'pages#summary', as: :summary
  get 'load_pictures' => 'pages#load_pictures', as: :picture
  get 'search' => 'pages#search', as: :search
  get 'price' => 'pages#price', as: :price
  get 'contact_us' => 'pages#contact_us', as: :contact_us
  post 'email_us' => 'pages#email_us', as: :email_us

  resources :subscriptions

  resources :tag_entries

  resources :opinions

  resources :beta_sign_ups, only: [:index, :create] do
    member do
      get :approve
      get :deny
      get :register
    end
  end

  resources :comments do
    collection do
      get :filter_sort
    end
  end

  resources :pictures
  resources :posts do
    member do
      post :judge
    end
  end

  resources :project_memberships do
    member do
      get :toggle
    end
  end

  resources :projects do
    collection do
      post :join_by_code
    end
    member do
      post :show
      get :management
      get :generate_code
    end
  end

  resources :organizations do
    member do
      get :toggle
      get :manage_users
      post :manage_users
      post :update_departments
    end
  end

  resources :user_sessions

  resources :users do
    member do
      get :my_organization
    end

    collection do
      get :autocomplete_user_email
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessor :username
  attr_accessor :new_subscription

  has_many :posts
  has_one :picture
  accepts_nested_attributes_for :picture

  has_many :comments, through: :posts

  has_many :department_entries, as: :context
  # has_many :posts, through: :department_entries

  has_many :department_entry_memberships, through: :department_entries
  has_many :users, through: :department_entry_memberships

  DEP_LIMIT = 5

  validates :name, uniqueness: true

  has_many :managers, -> {where(manager: true)}, class_name: 'User'
  has_many :admins, -> {where(admin: true)}, class_name: 'User'

  has_many :subscriptions
  has_one :active_subscription, -> { where(active: true) }, class_name: "Subscription"

  def organization_signup_email
    OrganizationsMailer.notify_clinton(self).deliver_now
  end

  def departments
    self.department_entries.map{|x| x.department_name}
  end

  def new_token
  	access_token = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
  	self.update_attributes(:access_token => access_token)
  end

  def activity_count
    (self.posts.count + self.comments.count)
  end

  def doit_post_count
    self.posts.select{|x| x.doit?}.count
  end

  def doit_comment_count
    self.comments.select{|x| x.doit?}.count
  end

  def doit_count
    self.doit_post_count + self.doit_comment_count
  end

  def toggle_activation_status!
    activation_status = self.activated
    if activation_status == false && self.update(activated: !activation_status)
      self.managers.each do |m|
        OrganizationsMailer.notfify_manager_of_approval(m).deliver_now
      end
    else
      false
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :generate_code, :toggle]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.order(:activated)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
    pics = @organization.build.picture
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @organization.access_token = ('a'..'z').to_a.shuffle[0,32].join

    respond_to do |format|
      if @organization.save
        OrganizationMembership.create(user_id: current_user.id, organization_id: @organization.id, admin: true)
        params[:departments].each do |d_id|
          DepartmentEntry.create(context: @organization, department_id: d_id)
        end
        format.html { redirect_to :dashboard, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    respond_to do |format|
      if @organization.toggle_activation_status!
        format.html {
          redirect_to :back, notice: 'Organization activation status toggled.'
        }
      else
        format.html {
          flash[:error] = "Could not toggle organization's activation status. Please try again later"
          redirect_to :back
        }
      end
    end
  end

  # def generate_code
  #   @prev = @organization.access_token
  #   @new = ('a'..'z').to_a.shuffle[0,32].join
  #   @organization.update_attribute(:access_token, @new)
  #   @user = current_user
  #   @url = Rails.env.production? ? request.host : request.host_with_port
  #   Notifier.register_form(@user, @organization,@url).deliver_now
  #   @organization.delay(run_at: 1.day.from_now).update_attribute(:access_token, nil)
  #   @time = Time.now
  #   redirect_to :back, notice: 'New access code generated.'
  # end

  # def join_by_code
  #   target_organization = Organization.where(name: params[:name]).first

  #   if target_organization.nil?
  #     redirect_to :back, notice: 'Organization does not exist.' and return
  #   end

  #   if target_organization.access_code != params[:access_code]
  #     redirect_to :back, notice: 'Wrong access code.' and return
  #   end

  #   OrganizationMembership.create(organization_id: target_organization.id, user_id: params[:user_id], admin: false)
  #   redirect_to target_organization, notice: 'Successfully joined organization.'
  # end

  # POST /organizations/1/manage_users
  def manage_users
    # if ask to manage users
    if !params[:department_entry_id].nil?
      @url = Rails.env.production? ? request.host : request.host_with_port
      @department_entry = DepartmentEntry.find(params[:department_entry_id])
      @organization = current_organization

      params[:invitee_list].split(/[,;]/).each do |target_email|
        next if target_email.blank?
        @user = User.where(email: target_email).first
        if @user.nil?
          # generate invite, send email
          existing_invite = UserInvite.where(user_id: current_user.id, email: target_email, department_entry: @department_entry, organization: current_organization).first
          if !existing_invite
            UserInvite.create(email: target_email, department_entry: @department_entry, organization: current_organization, user: current_user)
          end
        else
          # add & send email about update
          existing_membership = DepartmentEntryMembership.where(department_entry: @department_entry, user: @user).first
          if !existing_membership
            DepartmentEntryMembership.create(department_entry: @department_entry, user: @user)
          end
        end
      end
      params[:admin_list].split(/[,;]/).each do |target_email|
        @user = User.where(email: target_email).first
        if @user.nil?
          # generate invite, send email, decision maker
          existing_invite = UserInvite.where(user: current_user, email: target_email, department_entry: @department_entry, organization: current_organization).first
          if !existing_invite
            UserInvite.create(email: target_email, department_entry: @department_entry, admin: true, organization: current_organization)
          elsif !existing_invite.admin
            existing_invite.update(admin: true)
          end
        else
          # add & send email about update, decision maker
          existing_membership = DepartmentEntryMembership.where(department_entry: @department_entry, user: @user).first
          if !existing_membership
            DepartmentEntryMembership.create(department_entry: @department_entry, user: @user)
          elsif !existing_membership.admin
            existing_membership.update(admin: true)
          end
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def update_departments
    # set new department entries
    @organization.department_entries.each{|x| x.destroy}
    params[:departments].each do |d_id|
      DepartmentEntry.create(context: @organization, department_id: d_id)
    end
    redirect_to :back
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    @pic = Picture.new
    if params[:organization][:pictures] != nil
      @pic.image = params[:organization][:pictures][:image]
      if @pic.save
        @organization.picture = @pic
        @organization.save
      end
    end
    if @organization.update(organization_params)
      if organization_params[:new_subscription]
        Subscription.create(organization_id: @organization.id,
          end_at: organization_params[:new_subscription].to_date,
          subscription_type: 'standard', active: true)
      end
      redirect_to :back
    else
      @pic.delete
      redirect_to :back
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :access_token, :twitter_handle, :twitter_widget_id, :facebook_page_handle, :new_subscription)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
- if can? :manage, :all
  .admin-dashboard.col-sm-8.col-sm-offset-2
    %h3 Subscriptions

    %table.table
      %tr
        %th Name
        %th Activated?
        %th Active Subscription
        %th
        %th
        %th

      - @organizations.each do |organization|
        %tr
          %td= organization.name
          %td
            = organization.activated ? 'Yes' : 'No'
          %td
            - if organization.active_subscription.nil?
              = form_for organization do |f|
                = f.date_field :new_subscription
                = f.submit 'Update', class: 'btn btn-option'
            - else
              Active until:
              = organization.active_subscription.end_at.strftime('%b %d, %Y')
              = form_for organization.active_subscription do |f|
                = f.hidden_field :active, value: false
                = f.submit 'Revoke', class: 'btn btn-option'
          %td
            = link_to toggle_organization_path(organization) do
              Toggle Activation
              %i.fa.fa-retweet
          %td
          %td= link_to 'Destroy ×', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }
        - organization.managers.each do |manager|
          %tr.bg-white
            %td= "#{'&nbsp;'*10}#{manager.first_name} #{manager.last_name}".html_safe
            %td= "#{manager.email}".html_safe
            %td
            %td
            %td
            %td
            %td
- else
  %h3 You are not authorized to view this page.

app/views/organizations/manage_users.js.erb
$('.user_managment_wrapper').html("<%= j render(:partial => 'pages/user_management') %>");
$("#user_management").modal('show');

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

app/views/organizations/show.html.haml
%h2
  = @organization.name

  - if can? :update, @organization
    = link_to edit_organization_path(@organization) do
      .fa.fa-edit

- if can? :manage, @organization
  - if @organization.access_token != nil
    %h5
      %b Access code:
      = @organization.access_token

  = link_to generate_code_organization_path(@organization),:confirm => 'Token Expires in 1 min' do
    .btn.btn-sm.btn-success
      Generate New Code

%hr

%h3
  Projects
= link_to 'Create New Project', new_project_path(organization_id: @organization.id), class: "btn btn-success"
%br
%br
- if @organization.projects.empty?
  This organization doesn't have any projects yet.
- else
  - @organization.projects.each do |project|
    = render "projects/card", project: project